# create word lists

book_title_list = ["Tango in Tansania",
                  "Laptopkabel aufgebraucht",
                  "Kaffee und Kuchen mit Helmut Sonderbarke",
                   "Die Reise nach Danzig",
                   "Das Zelt am Rheinstrand",
                   "Moritz und Max",
                   "In einer Stunde von Köln nach Bonn",
                   "Laura fährt ans Meer",
                   "Unser Hund Roku",
                   "In die Fresse",
                   "Hau drauf",
                   "Das geht rum",
                   "Bitter",
                   "Pommes und Champagner",
                   "Lachen, Weinen, Blutwurst",
                   "Herz 10, Karo Ass",
                   "Der gute Mensch von Sezuan am Strand",
                   "Warum habe ich immer so kalte Füße?",
                   "Wenn die Sonne über Nairobi versinkt",
                   "Als wir noch jung und knackig waren",
                   "Als Jochen und Johanna sich noch liebten",
                   "Die japanischen Fliesenleger",
                   "Einhundert Meter bis Lichtenberg",
                   "Leichtsinn und Schwermut",
                   "Mein Leiden und Lieben. Die ganze Geschichte von Willi Millowitsch",
                  "Die geilen Strolche",
                   "Willst du mit mir gehen?",
                   "Als Nena mir einen Handkuss zuwarf.",
                   "Warum ich den Wendler mag.",
                   "Cäsars Füße",
                   "Die Gemächer der Zofe",
                   "Auf eine Zigarette mit Axel Stein",
                   "Der Wind der pfiff und wir lauschten",
                  "Zeit: Eine Geschichte des Wartens.",
                  "Les morses incroiables et dignificée",
                   "Lorum bonus ipsarem",
                   "Warum wir nicht gehen wohin wir kommen",
                   "Von der unnachahmlichen Erträglichkeit seines Leichtsinns",
                   "Unterleutnant",
                   "Shoppen in Paris mit den bitches",
                   "Karl fährt aufs Meer",
                   "Schocker",
                   "Kochen auf Grönländisch",
                   "Grundsatz. Eine Annäherung",
                   "Angela Merkel und ihre Beziehung zu Hunden. Eine Abrechung",
                   "Was Schoppenhauer und Boateng gemeinsam haben. Eine wilde Reise durch die Philosophie"]

adjective_list = ["verschwurbelten",
                  "brachialen",
                  "gewaltverherrlichenden",
                  "melancholischen",
                  "mystischen",
                  "geradlinigen",
                  "asymmetrisch erzählten",
                  "kafkaesken",
                  "epochalen",
                  "lebendigen",
                  "ermüdenden",
                  "schweren",
                  "leichten",
                  "beglückenden",
                  "erquickenden",
                  "fadenscheinigen",
                  "französisch angehauchten",
                  "hinreißenden",
                  "verrückten",
                  "tiefgründigen",
                  "langweiligen",
                  "ästethisch ansprechenden",
                  "verrückten",
                  "martialischen"]
objekt_list = [["Kurzgeschichte","f"],
               ["Kochbuch","m"],
               ["Riesenschinken","m"],
               ["Unterhosenposse","f"],
               ["Abrechnung","f"],
               ["literatischen Goldstück","m"],
               ["Schmonzette","f"],
               ["Italo-Romanze","f"],
               ["Schundroman","m"],
               ["Hauptwerk","m"],
               ["Provinzposse","f"],
               ["Parodie","f"],
               ["Thriller","m"],
               ["Schlüsselroman","m"],
               ["Verriss","m"],
               ["Dreigroschenroman","m"],
               ["Porno-Novelle","f"],
               ["Kleinod","m"],
               ["Schinken","m"]]

verb_list = [["umreißt","",""],
             ["beschreibt","",""],
             ["verarbeitet","",""],
             ["erläutert","",""],
             ["schildert","",""],
             ["referiert","über",""],
             ["feiert","",""],
             ["bebildert","",""],
             ["stellt","","dar"],
             ["ergründet","",""],
             ["verreißt","",""],
             ["kritisiert","",""],
             ["erklärt","",""],
             ["beschmutzt","",""],
             ["analysiert","",""],
             ["zerstört","",""],
             ["persifliert","",""],
             ["verspottet","",""],
             ["intepretiert",""],"",
             ["veranschaulicht","",""],
             ["schreibt", "über",""],
             ["erzählt", "über",""],
             ["zieht","über", "her"],
             ["kackt", "über", "ab",],
             ["regt", "sich über", "auf"],
             ["echauffiert sich"," über",""],
             ["erregt sich","an",""],
             ["","",""],
             ]


was_list = ["das Leben",
            "die Irrungen und Wirrungen",
            "alle schmutzigen Geheimnisse",
            "die zeitlose Schönheit aber auch das Leiden",
            "die bewegten Jahre",
            "die tiefgründigen Liebschaften",
            "das Leben und Wirken",
            "die heiklen Beziehungen",
            "die ausschweifenden Völlereien",
            "das unglaubliche Talent aber auch die tiefen Abgründe",
            "den Lebensweg",
            "die kriegerischen Auseinandersetzungen",
       "den langsamen Prozess des Verfalls",
       "die täglichen Einkaufsgeschäfte",
       "den trockenen und extrem faden Geschlechtsverkehr",
       "die wilde Jugendzeit",
            "das heimliche Verlangen",
            "viele unschöne und nachhaltig verstörende Geschichten",
            "die Herkunfsgeschichte und den Werdegang",
            "das große Lebenswerk",
            "die zahllosen Liebschaften und Affären",
            "das Leben und Leiden",
            "die größten Peinlichkeiten"]
wessen_list = ["des frühen Louis XIV",
               "der zypriotischen Holzfäller",
               "des jungen Thomas Mann",
               "des Flügels der AfD",
               "Jürgen Tritins und weiterer neo-enviromentalisischer Fundamentalisten",
               "der alaskischen Teppichweber",
               "der Jugend in den 2000ern",
               "der Pre-Smartphone Generationen",
               "jener Generationen, die noch ohne Alexa aufgewachsen sind",
               "der Wuppertaler Rentner-Community",
               "unserer Großeltern",
               "der woken Berliner Community",
               "dreier kleiner süßer Hunde",
               "Astrid Lindgrens und ihrer Familie",
               "der kaukasischen Brunnenputzerfrauen",
               "von Helmut Schmidts Schuster",
               "des Mannes, der Giovanni di Lorenzo einmal versucht hat einen Staubsauger zu verkaufen",
               "der deutschen Jugend",
               "der sächsischen Ureinwohner",
               "einer sprechenden Stecknadel"]
wowann_list = ["zur Zeit der Kirschblüte",
               "und hält so der spätkapitalistischen Postmoderne den Spiegel vor.",
               "im modernen Finnland",
               "und geht mit seinen spitzfindigen Analysen dahin, wo es besonders jenen, die sich auf der moralischen Sonnenseite der Gesellschaft wähnen, weh tut",
               "beim täglichen Auf und Ab von Lust und Verlangen",
               "und berührt dabei auch die verschiedenen Spielarten des Neoexistenzialismus",
               "auf verstörende Art und Weise",
               "extrem schlecht",
               ". Ich fand das Buch geil, aber ich glaub, es ist eigentlich scheiße.",
               "und bewegt dabei durch seine eindringlichen Schilderungen der Buxtehuder Nachkriegszeit",
               "und spart dabei auch nicht mit Referenzen zu Thomas Mann und anderen Literaten der Weimarer Zeit",
               "",
               "und verstört dabei nicht nur eingefleischte Krimifans, sondern auch alle anderen, die sich gehobene Lektüre erhofft hatten"
               "zur Zeit des dritten Reiches",
               "in unnachahmlicher Weise",
               "auf eindrucksvolle Art und Weise",
               "einfühlsam",
               ". Eine übler und verstörrender Versuch, die Errungenschaften Gerhard Schröders während seiner Kanzlerschaft zu untergraben",
               "und spart dabei auch nicht mit Kritik an den frühen Werken von Juli Zeh",
               ". Ein Must-Read für jeden, der sich auch mit aufkeimender Politikverdrossenheit noch für Fragen des Neokorporatismus begeistern kann.",
               "sensibel und zeitgemäß",
               ", ohne dabei zu vergessen, auch die Hintergründe der eigenen Biografie kritisch zu hinterfragen",
               ""]
